### ISSUE TITLE
ISSUES.md 파일은 의도된 파일인가요?

### ISSUE THREAD

**Issue by Sayakie** [Danue1/danube#1]
안녕하세요. Danube를 살펴보다가 [ISSUES.md](https://github.com/Danue1/danube/blob/5b4eb39a7c23f60e5778063876e264e4f1c81d5a/ISSUES.md) 파일을 보게 되었는데, 잘못 커밋된 파일로 보여서 이슈 남깁니다.

아니면 혹시 의도된 파일일까요?

**Comment by Danue1** [comment]
또잉, 그렇네요.
Git History에 남겨놔도 일단은 문제가 없을듯 해서 삭제하는 커밋을 추가했습니다.
제보 감사합니다.
